### ISSUE TITLE
Compatibilité v7

### ISSUE THREAD

**Issue by philippe-opendsi** [ATM-Consulting/dolibarr_module_inventory#23]
Bonjour
Le module utilise le champs label dans ses requêtes sur la table entrepot qui a disparu au profit du champs ref d'où quelques soucis lors de la création d'un inventaire.
Remplacement vu à faire  au moins dans inventory.php et inventory.lib.php et dans le core...
Je continue mes tests et reviens vers vous si je vois d'autres soucis

**Comment by atm-john** [comment]
Il semble que c'est géré maintenant
