### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by Toyin123** [ATM-Consulting/dolibarr_module_inventory#7]
Salut actuellement en école d’ingénieur,notre projet consiste a la mise en place d'un ERP pour une entreprise  je voudrais savoir quelle est la fonction exacte de votre module.
S'agit-il d'un WMS ? Comme on l'entend

**Comment by atm-alexis** [comment]
Bonjour,

Dolibarr n'est pas a proprement parlé un WMS même s'il peut en assurer les fonctions de base. Ce module lui permet la valorisation et la régulation de l'inventaire, ce qui est UNE fonction parmi tant d'autre d'un WMS.

Cdlt,

**Comment by Toyin123** [comment]
Vous entendez quoi par la valorisation et la regulation ? avez d'autres modules qui s'en rapprochent ou d'autres logiciels qui s'en rapprochent 
Merci.

**Comment by atm-alexis** [comment]
Dolibarr support les fonctionnalités principales d'un WMS https://fr.wikipedia.org/wiki/Warehouse_management_systems

Par contre il n'est pas un WMS dédié (seconde partie de wikipedia). Concernant la valorisation et la régulation de stock, ce sont des notions fondamentales d'un inventaire qui sert à corriger une données de stock par une réalité (régulation) et obtenir le montant des marchandises stockées (valorisation). Je ne peux malheureusement pas prendre le temps de pousser plus avant l'explication et je vous laisse vous tourner vers votre client pour qui ces notions ne doivent pas être une inconnue.

Cdlt

**Comment by Toyin123** [comment]
Ok merci beaucoup pour votre aide.
